// Generated by CoffeeScript 1.4.0
(function() {
  var $, $document, activeKeys, converter, ctrl, lastHTML, lastText, m, markdownify, showdown;

  activeKeys = [];

  ctrl = 17;

  m = 77;

  $ = require('jquery');

  showdown = require('./vendor/showdown.js');

  converter = new showdown.converter();

  $document = $(document);

  lastHTML = lastText = null;

  $document.keydown(function(event) {
    var key;
    key = event.keyCode;
    activeKeys[key] = true;
    if (activeKeys[ctrl] && activeKeys[m]) {
      return markdownify(event);
    }
  });

  $document.keyup(function(event) {
    var key;
    key = event.keyCode;
    return activeKeys[key] = false;
  });

  markdownify = function(event) {
    var $el, html, value;
    if (event == null) {
      event = null;
    }
    if (typeof event.preventDefault === "function") {
      event.preventDefault();
    }
    $el = $(':focus');
    value = $el.val();
    if (!value) {
      return;
    }
    if (value === lastHTML) {
      return $el.val(lastText);
    }
    lastText = value;
    html = converter.makeHtml(value);
    lastHTML = html;
    return $el.val(html);
  };

}).call(this);
