// Generated by CoffeeScript 1.4.0
(function() {
  var $, $document, activeKeys, converter, ctrl, m, markdownify, showdown, subscribe;

  subscribe = document.getElementById('subscribe');

  if (subscribe) {
    subscribe.checked = true;
  }

  activeKeys = [];

  ctrl = 17;

  m = 77;

  $ = require('jquery');

  showdown = require('./vendor/showdown.js');

  converter = new showdown.converter();

  $document = $(document);

  $document.keydown(function(event) {
    var key;
    key = event.keyCode;
    activeKeys[key] = true;
    if (activeKeys[ctrl] && activeKeys[m]) {
      return markdownify(event);
    }
  });

  $document.keyup(function(event) {
    var key;
    key = event.keyCode;
    return activeKeys[key] = false;
  });

  markdownify = function(event) {
    var $el, html;
    if (event == null) {
      event = null;
    }
    if (typeof event.preventDefault === "function") {
      event.preventDefault();
    }
    $el = $(':focus');
    if (!$el.val()) {
      return;
    }
    html = converter.makeHtml($el.val());
    return $el.val(html);
  };

}).call(this);
